drop view if exists gold.table_combined;
create view gold.table_combined as 
	select gps_provider,
		p.booking_ID,
		market_regular,
		booking_ID_date,
		vehicle_no,
		p.origin_location,
		p.destination_location,
		r.region,
		org_lat,
		org_lon,
		des_lat,
		des_lon,
		data_ping_time,
		planned_eta,
		curr_location,
		des_location,
		actual_eta,
		curr_lat,
		curr_lon,
		ontime,
		delay,
		r.on_time_delivery,
		r.customer_rating,
		r.condition_text,
		r.fixed_costs,
		r.maintenance,
		r.different,
		r.area,
		r.delivery_time,
		origin_location_code,
		destination_location_code,
		trip_start_date,
		trip_end_date,
		distance_in_km,
		vehicle_type,
		minimum_kms_covered_in_day,
		driver_name,
		driver_phone_no,
		customer_id,
		customer_name_code,
		supplier_id,
		supplier_name_code,
		material_shipper
	from silver.Transportation_Primary as p
	left join silver.Transportation_Refined as r
	on p.booking_id = r.delivery_id;