drop table if exists silver.Transportation_Primary ;
create table silver.Transportation_Primary (
	gps_provider text,
	booking_ID text,
	market_regular varchar(30),
	booking_ID_date date,
	vehicle_no text,
	origin_location text,
	destination_location text,
	org_lat float,
	org_lon float,
	des_lat float,
	des_lon float,
	data_ping_time interval,
	planned_eta interval,
	curr_location text,
	des_location text,
	actual_eta timestamp,
	curr_lat float,
	curr_lon float,
	ontime varchar(30),
	delay varchar(30),
	origin_location_code text,
	destination_location_code text,
	trip_start_date timestamp,
	trip_end_date timestamp,
	distance_in_km float,
	vehicle_type text,
	minimum_kms_covered_in_day float,
	driver_name text,
	driver_phone_no text,
	customer_id text,
	customer_name_code text,
	supplier_id text,
	supplier_name_code text,
	material_shipper text,
	data_create_date timestamp default current_timestamp
);

drop table if exists silver.Transportation_Refined;
create table silver.Transportation_Refined (
	delivery_id text,
	origin_location text,
	destination_location text,
	region varchar(50),
	created_at timestamp,
	actual_delivery_time timestamp,
	on_time_delivery boolean,
	customer_rating int,
	condition_text text,
	fixed_costs int,
	maintenance int,
	different int,
	area varchar(50),
	delivery_time int,
	data_create_date timestamp default current_timestamp
);