-- 1.What are the total car sales by year?
select extract(year from date) as year,
	count(car_id) as num_car_sell
from car_sales
group by year; 

-- 2.Which car brands have the highest sales volume?
select company, count(*) as num_car_sell
from car_sales
group by company
order by num_car_sell desc; 

-- 3.What is the most sold car model for each brand?
with car_sell_per_com as (
	select company, model, count(*) as num_car_sell
	from car_sales
	group by company, model
),
ranking as(
	select company, model, num_car_sell,
		row_number() over (partition by company order by num_car_sell desc) as rn
	from car_sell_per_com
)
select company, model, num_car_sell
from ranking
where rn =1; 

-- 4.What is the average price of cars sold by each brand?
select company, round(avg(price),2) as avg_price
from car_sales
group by company; 

-- 5.What is the distribution of car sales by transmission type?
select transmission, 
	round(100.0*count(*)/(select count(car_id) from car_sales),2) as percentage
from car_sales 
group by transmission; 

-- 6.Which body styles are the most popular across all regions?
select bodystyle, count(*) as num_car
from car_sales
group by bodystyle 
order by num_car desc; 

-- 7.What is the percentage contribution of each brand to total sales?
select company, 
	round(100.0*sum(price)/ (select sum(price) from car_sales),2) as percentage
from car_sales
group by company
order by percentage desc;

-- 8.How do sales vary across different fuel types?
select engine, count(*) as num_car_sell
from car_sales
group by engine ;

-- 9.Which color is the most popular among customers?
select color, count(*) as num_car_sell
from car_sales
group by color
order by num_car_sell desc;

-- 10.What is the total revenue generated by each dealer?
select dealer_name, sum(price) as total_sale
from car_sales
group by dealer_name; 

-- 11.What is the gender distribution of customers?
select gender, 
	round(100.0*count(*)/(select count(*) from car_sales),2) as percentage
from car_sales 
group by gender; 

-- 12.What is the average annual income of customers who purchased cars?
select round(avg(annualincome),2) as avg_annual_income
from car_sales;

-- 13.Are there specific car brands or models preferred by male vs. female customers?
with sale_by_com as (
	select model, gender, count(*) as num_of_sale,
		sum(count(*)) over (partition by model) as sale_per_company
	from car_sales
	group by model, gender 
)
select model, gender, num_of_sale,
	round(100.0*num_of_sale/sale_per_company,2) as percentage
from sale_by_com;

-- 14.What is the correlation between annual income and car price?
select corr(annualincome, price) as corr	
from car_sales;

-- 15.How does customer phone data (if any) reflect dealer preferences?
select dealer_name, count (distinct phone) as distinct_cus
from car_sales
group by dealer_name;

-- 16.How many unique customers purchased cars during the dataset's timeframe?
select count(distinct phone) as num_of_cus
from car_sales;

-- 17.What is the median annual income of customers for each dealer?
select dealer_name, 
	percentile_cont(0.5) within group (order by annualincome) as median
from car_sales
group by dealer_name; 

-- 18.Are there any patterns in gender preferences for specific car colors?
with sale_by_color as (
	select color, gender, count(*) as num_of_sale,
		sum(count(*)) over (partition by color) as sale_per_color
	from car_sales
	group by color, gender 
)
select color, gender, num_of_sale,
	round(100.0*num_of_sale/sale_per_color,2) as percentage
from sale_by_color;

-- 19.Which regions have the highest car sales volume?
select dealer_region, count(car_id) as num_car_sell
from car_sales
group by dealer_region 
order by num_car_sell desc; 

-- 20.What are the top-performing dealers in each region?
with ranking_dealer as (
	select dealer_region, dealer_name, count(car_id) as num_of_car,
		row_number() over (partition by dealer_region order by count(car_id) desc) as rn
	from car_sales
	group by dealer_region, dealer_name 
)
select dealer_region, dealer_name, num_of_car
from ranking_dealer 
where rn = 1;

-- 21.How does car price vary across different regions?
select dealer_region,
	case when price <= 5000 then 'Low price'
		 	when price > 5000 and price <=10000 then 'Low-middle price'
		 	when price > 10000 and price <=30000 then 'Medium price'
			when price > 30000 and price <= 50000 then 'Medium-high price'
			when price > 50000 and price <= 80000 then 'High price'
			else 'Expensive'
	end as price_group,
	count(*) as num_of_car
from car_sales
group by price_group, dealer_region
order by dealer_region, price_group;

-- 22.What is the total revenue generated by each region?
select dealer_region, sum(price) as total_revenue
from car_sales
group by dealer_region;

-- 23.Are there specific car models that sell better in certain regions?
with ranking as (
	select dealer_region, model, count(*) as num_of_car,
		row_number() over (partition by dealer_region order by count(*) desc) as rn
	from car_sales
	group by dealer_region, model
)
select dealer_region, model, num_of_car
from ranking
where rn =1; 

-- 24.What is the sales trend for each region over time?
select dealer_region,
	extract (year from date) as year,
	extract(month from date) as month, 
	count(*) as num_car_sales
from car_sales 
group by month, year, dealer_region 
order by dealer_region, year, month;

-- 25.Which regions have the highest average customer income?
select dealer_region, avg(annualincome) as avg_annualincome
from car_sales
group by dealer_region
order by avg_annualincome desc;

-- 26.How do car sales vary month by month?
select
	extract (year from date) as year,
	extract(month from date) as month, 
	count(*) as num_car_sales
from car_sales 
group by month, year
order by year, month;

-- 27.What is the peak sales period for each brand?
select company,
	extract (year from date) as year,
	extract(month from date) as month, 
	count(*) as num_car_sales
from car_sales 
group by company, month, year
order by company, num_car_sales desc;

-- 28.What are the most sold car models during the holiday seasons?
with seasonal as (
	select case 
		when to_char (date, 'MM-DD') between '11-15' and '12-26' then 'Thank givings, Christmas season'
		when to_char (date, 'MM-DD') between '07-01' and '07-06' then 'Independence season'
		when to_char (date, 'MM-DD') between '05-20' and '05-31' then 'Memmorial season'
		else 'Normal day'
		end as seasonal,
		model,
	count(*) as num_car_sell
	from car_sales
	group by seasonal, model 
),
ranking as (
	select seasonal, model, num_car_sell,
		row_number() over (partition by seasonal order by num_car_sell desc) as rn 
	from seasonal
	where seasonal != 'Normal day'
)
select seasonal, model, num_car_sell
from ranking
where rn =1; 
	
-- 29.How does the revenue trend evolve over the years?
select extract(year from date) as year,
sum(price) as revenue
from car_sales
group by year; 

-- 30.What is the average price of cars sold each month?
select extract(month from date) as month,
avg(price) as avg_price 
from car_sales
group by month; 

-- 31.What is the year-over-year growth rate of sales?
with next_year_sale as (
	select extract(year from date) as year,
	sum(price) as revenue,
	lead(sum(price)) over (order by extract(year from date)) as next_year_revenue 
	from car_sales
	group by year
)
select year, revenue,next_year_revenue,
	round(100.0*(next_year_revenue - revenue)/next_year_revenue,2) as growth_rate
from next_year_sale
where next_year_revenue is not null; 

-- 32.Which dealer has the highest total sales revenue?
select dealer_name, 
	sum(price) as total_sales
from car_sales
group by dealer_name
order by total_sales desc; 

-- 33.What is the average price of cars sold by each dealer?
select dealer_name, 
	round(avg(price),2) as avg_sales
from car_sales
group by dealer_name;

-- 34.Which dealer sells the most expensive cars on average?
select dealer_name, price 
from car_sales
where dealer_name in (
	select dealer_name
	from car_sales
	where price = (
		select max(price)
		from car_sales )
)
order by price desc
limit 1;

-- 35.How many unique car models does each dealer sell?
select dealer_name, 
	count(distinct model) as unique_count
from car_sales
group by dealer_name; 

-- 36.What is the sales volume of each dealer by region?
select dealer_region, dealer_name, count(*) as num_car_sales
from car_sales
group by dealer_region, dealer_name
order by dealer_region

-- 37.Which dealers dominate in terms of revenue in specific regions?
with ranking as (
	select dealer_region, dealer_name, 
		sum(price) as total_revenue,
		row_number() over (partition by dealer_region order by sum(price) desc) as rn
	from car_sales
	group by dealer_region, dealer_name
)
select dealer_region, 
		dealer_name, 
		total_revenue
from ranking
where rn =1;

-- 38.What is the median car price in the dataset?
select percentile_cont(0.5) within group (order by price) as median
from car_sales; 

-- 39.How many cars are sold within specific price ranges (e.g., <$20,000, $20,000-$40,000, etc.)?
select
	case when price <= 5000 then 'Low price'
		 	when price > 5000 and price <=10000 then 'Low-middle price'
		 	when price > 10000 and price <=30000 then 'Medium price'
			when price > 30000 and price <= 50000 then 'Medium-high price'
			when price > 50000 and price <= 80000 then 'High price'
			else 'Expensive'
	end as price_group,
	count(*) as num_of_car
from car_sales
group by price_group;

-- 40.What is the total revenue generated by each brand?
select company, sum(price) as total_revenue
from car_sales
group by company 
order by total_revenue desc; 

-- 41.What is the price range for the top 5 most sold car models?
with top_5 as (
	select model, count(*) as num_car_sales
	from car_sales
	group by model
	order by num_car_sales desc
	limit 5
)
select model, 
	min(price) as min_price,
	max(price) as max_price
from car_sales
where model in (
	select model
	from top_5
)
group by model;

-- 42.Which car models contribute most significantly to total revenue?
-- select * from car_sales


-- 43.How does the popularity of car brands evolve over time?
-- 44.What is the sales trend for each car model?
-- 45.Which car models have the best sales-to-price ratio?
-- 46.Are there brands that dominate in specific transmission types or engine configurations?
-- 47.Which models have the lowest average price but high sales volume?
-- 48.What is the relationship between engine size and car price?
-- 49.How does the dealer's region influence the choice of car color?
-- 50.What is the customer lifetime value (CLV) based on repeat purchases?