-- 1.What are the total car sales by year?
select extract(year from date) as year,
	count(car_id) as num_car_sell
from car_sales
group by year; 

-- 2.Which car brands have the highest sales volume?
select company, count(*) as num_car_sell
from car_sales
group by company
order by num_car_sell desc; 

-- 3.What is the most sold car model for each brand?
with car_sell_per_com as (
	select company, model, count(*) as num_car_sell
	from car_sales
	group by company, model
),
ranking as(
	select company, model, num_car_sell,
		row_number() over (partition by company order by num_car_sell desc) as rn
	from car_sell_per_com
)
select company, model, num_car_sell
from ranking
where rn =1; 

-- 4.What is the average price of cars sold by each brand?
select company, round(avg(price),2) as avg_price
from car_sales
group by company; 

-- 5.What is the distribution of car sales by transmission type?
select transmission, 
	round(100.0*count(*)/(select count(car_id) from car_sales),2) as percentage
from car_sales 
group by transmission; 

-- 6.Which body styles are the most popular across all regions?
select bodystyle, count(*) as num_car
from car_sales
group by bodystyle 
order by num_car desc; 

-- 7.What is the percentage contribution of each brand to total sales?
select company, 
	round(100.0*sum(price)/ (select sum(price) from car_sales),2) as percentage
from car_sales
group by company
order by percentage desc;

-- 8.How do sales vary across different fuel types?
select engine, count(*) as num_car_sell
from car_sales
group by engine ;

-- 9.Which color is the most popular among customers?
select color, count(*) as num_car_sell
from car_sales
group by color
order by num_car_sell desc;

-- 10.What is the total revenue generated by each dealer?
select dealer_name, sum(price) as total_sale
from car_sales
group by dealer_name; 

-- 11.What is the gender distribution of customers?
select gender, 
	round(100.0*count(*)/(select count(*) from car_sales),2) as percentage
from car_sales 
group by gender; 

-- 12.What is the average annual income of customers who purchased cars?
select round(avg(annualincome),2) as avg_annual_income
from car_sales;
-- 13.Are there specific car brands or models preferred by male vs. female customers?
-- 14.What is the correlation between annual income and car price?
-- 15.How does customer phone data (if any) reflect dealer preferences?
-- 16.How many unique customers purchased cars during the dataset's timeframe?
-- 17.What is the median annual income of customers for each dealer?
-- 18.Are there any patterns in gender preferences for specific car colors?
-- 19.Which regions have the highest car sales volume?
-- 20.What are the top-performing dealers in each region?
-- 21.How does car price vary across different regions?
-- select * from car_sales


-- 22.What is the total revenue generated by each region?
-- 23.Are there specific car models that sell better in certain regions?
-- 24.What is the sales trend for each region over time?
-- 25.Which regions have the highest average customer income?
-- 26.How do car sales vary month by month?
-- 27.What is the peak sales period for each brand?
-- 28.What are the most sold car models during the holiday seasons?
-- 29.How does the revenue trend evolve over the years?
-- 30.What is the average price of cars sold each month?
-- 31.What is the year-over-year growth rate of sales?
-- 32.Which dealer has the highest total sales revenue?
-- 33.What is the average price of cars sold by each dealer?
-- 34.Which dealer sells the most expensive cars on average?
-- 35.How many unique car models does each dealer sell?
-- 36.What is the sales volume of each dealer by region?
-- 37..Which dealers dominate in terms of revenue in specific regions?
-- 38.What is the median car price in the dataset?
-- 39.How many cars are sold within specific price ranges (e.g., <$20,000, $20,000-$40,000, etc.)?
-- select case when annualincome <= 20000 then 'Low income'
-- 		 	when annualincome > 20000 and annualincome <=100000 then 'Low-middle income'
-- 		 	when annualincome > 100000 and annualincome <=200000 then 'Medium income'
-- 			when annualincome > 200000 and annualincome <=500000 then 'Medium-high income'
-- 			when annualincome > 500000 and annualincome <=1000000 then 'High income'
-- 			else 'Wealthy'
-- 	end as income_group,
-- 	case when price 


-- 40.What is the total revenue generated by each brand?
-- 41.What is the price range for the top 5 most sold car models?
-- 42.Which car models contribute most significantly to total revenue?
-- 43.How does the popularity of car brands evolve over time?
-- 44.What is the sales trend for each car model?
-- 45.Which car models have the best sales-to-price ratio?
-- 46.Are there brands that dominate in specific transmission types or engine configurations?
-- 47.Which models have the lowest average price but high sales volume?
-- 48.What is the relationship between engine size and car price?
-- 49.How does the dealer's region influence the choice of car color?
-- 50.What is the customer lifetime value (CLV) based on repeat purchases?